### PR TITLE
Add setup from external url.

### PR DESCRIPTION
**Pull request by q3dm17**
Added extension for configuring cluster client for working with singular via nginx.

### CODE REVIEW

**Comment by kungasc** [comment]
1. Seems something was missing comparing to [Kontur version](https://git.skbkontur.ru/ke/singular/-/blob/master/Kontur.Singular.Client/ExternalSingularClient.cs#L46)?

2. This is not actually `SetupSingularExternal`, because there is can be no Singular after nginx. This is just some `SetupExternalUrl`.

**Comment by q3dm17** [comment]
1. It's slightly differs from Kontur version: there we constructing whole IClusterClient instance, here we tuning given to extension instance. Because of this there is no transport setup, no tracing setup, no request deduplicating turning on.
2. Does it mean that this module is not a right place for this extension? Or it just about method naming and TargetServiceName tuning?

**Comment by kungasc** [comment]
> Does it mean that this module is not a right place for this extension? Or it just about method naming and TargetServiceName tuning?

Yes, not fill TargetServiceName  at all.

Also rename method.

Maybe module `vostok.clusterclient.extensions` would be better for that, but we do not have it :)

**Comment by iloktionov** [comment]
Closing as this PR is now superseded by https://github.com/vostok/clusterclient.core/pull/11.

**Pull request closed without merging**
